name: Deploy Fenics-legacy-jupyter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ env.SERVER_SSH_KEY }}

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: 22
          source: "."
          target: "~/fenics-legacy/"

      - name: Build and deploy Docker container on server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
            cd ~/fenics-legacy
            sudo docker build -t fenics-legacy .
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^fenics-legacy-container$'; then
              sudo docker stop fenics-legacy-container
              sudo docker rm fenics-legacy-container
            fi
            sudo docker run -d --name fenics-legacy-container -p 8887:8887 fenics-legacy
          EOF
